services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: flowstate-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: flowstate-kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka

  producer-db:
    image: postgres:15
    container_name: flowstate-producer-db
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB=transaction_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  consumer-db:
    image: postgres:15
    container_name: flowstate-consumer-db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=bonus_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4
    container_name: flowstate-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - producer-db
      - consumer-db